services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: permissions
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d permissions"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports: ["8080:8080"]


